### ISSUE TITLE
Steam API currently via http

### ISSUE THREAD

**Issue by ayyaya** [ayyaya/humblebundlelibrarysteamview#3]
The Steam API is currently called with http://. Users with "Only https"-Plugins for their browser don't get any results.

**Comment by forteller** [comment]
Ah, so that's why it wasn't working! Thanks!

Do you know if there's some URL I could add to the list of exceptions to make it work with the strict https mode?

**Comment by ayyaya** [comment]
This issue is now solved with the newest version 1.2, published at 24.04.2024 :)
